

DB_NAME = "database.db"

# CONFIG
SECRET_KEY = "numba1star"

SQLALCHEMY_DATABASE_URI = f"sqlite:///{DB_NAME}"
SQLALCHEMY_TRACK_MODIFICATIONS = False

# API KEYS
TMDB_API_KEY = "8784d04e148ccc0bdc003b1dc79e5483"
